"""create_diseases

Revision ID: 266d2a3e03c5
Revises: d5b113ed12fa
Create Date: 2025-04-30 14:27:39.592811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266d2a3e03c5'
down_revision: Union[str, None] = 'd5b113ed12fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_id'), 'diseases', ['id'], unique=False)
    op.create_table('leaf_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaf_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['leaf_id'], ['leafs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaf_diseases_id'), 'leaf_diseases', ['id'], unique=False)
    op.drop_column('leafs', 'treatment')
    op.drop_column('leafs', 'prevention')
    op.drop_column('leafs', 'diseases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leafs', sa.Column('diseases', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leafs', sa.Column('prevention', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leafs', sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leaf_diseases_id'), table_name='leaf_diseases')
    op.drop_table('leaf_diseases')
    op.drop_index(op.f('ix_diseases_id'), table_name='diseases')
    op.drop_table('diseases')
    # ### end Alembic commands ###
