"""create_segmentation

Revision ID: 297dc8b22d57
Revises: 936d8f0f5376
Create Date: 2025-05-03 13:32:14.580988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297dc8b22d57'
down_revision: Union[str, None] = '936d8f0f5376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segmentation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentation_types_id'), 'segmentation_types', ['id'], unique=False)
    op.create_table('segmentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_data', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentations_id'), 'segmentations', ['id'], unique=False)
    op.create_table('segmentaion_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('mask_path', sa.Text(), nullable=True),
    sa.Column('segmentation_id', sa.Integer(), nullable=True),
    sa.Column('segmentation_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segmentation_id'], ['segmentations.id'], ),
    sa.ForeignKeyConstraint(['segmentation_type_id'], ['segmentation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentaion_photos_id'), 'segmentaion_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segmentaion_photos_id'), table_name='segmentaion_photos')
    op.drop_table('segmentaion_photos')
    op.drop_index(op.f('ix_segmentations_id'), table_name='segmentations')
    op.drop_table('segmentations')
    op.drop_index(op.f('ix_segmentation_types_id'), table_name='segmentation_types')
    op.drop_table('segmentation_types')
    # ### end Alembic commands ###
