"""create_training_session

Revision ID: 74fe7b4279e2
Revises: 8477986467ae
Create Date: 2025-05-01 12:36:53.871130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fe7b4279e2'
down_revision: Union[str, None] = '8477986467ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('best_val_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_table('training_epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epoch_num', sa.Integer(), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('train_accuracy', sa.Float(), nullable=True),
    sa.Column('val_accuracy', sa.Float(), nullable=True),
    sa.Column('training_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_epochs_id'), 'training_epochs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_epochs_id'), table_name='training_epochs')
    op.drop_table('training_epochs')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
