"""update_plants

Revision ID: 7e646007cf96
Revises: b425c3d075da
Create Date: 2025-04-29 14:47:13.415324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e646007cf96'
down_revision: Union[str, None] = 'b425c3d075da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'user_id')
    # ### end Alembic commands ###
