"""create_ai_plant

Revision ID: 8477986467ae
Revises: 266d2a3e03c5
Create Date: 2025-04-30 16:52:38.436436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8477986467ae'
down_revision: Union[str, None] = '266d2a3e03c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_plants_id'), 'ai_plants', ['id'], unique=False)
    op.create_table('ai_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_types_id'), 'ai_types', ['id'], unique=False)
    op.create_table('ai_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('ai_plant_id', sa.Integer(), nullable=True),
    sa.Column('ai_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ai_plant_id'], ['ai_plants.id'], ),
    sa.ForeignKeyConstraint(['ai_type_id'], ['ai_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_photos_id'), 'ai_photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_photos_id'), table_name='ai_photos')
    op.drop_table('ai_photos')
    op.drop_index(op.f('ix_ai_types_id'), table_name='ai_types')
    op.drop_table('ai_types')
    op.drop_index(op.f('ix_ai_plants_id'), table_name='ai_plants')
    op.drop_table('ai_plants')
    # ### end Alembic commands ###
