"""create_photo_plant

Revision ID: afac0c636b80
Revises: 68e4c6298a61
Create Date: 2025-04-29 11:11:10.456789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afac0c636b80'
down_revision: Union[str, None] = '68e4c6298a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leafs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leafs_id'), 'leafs', ['id'], unique=False)
    op.create_table('plant_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_photos_id'), 'plant_photos', ['id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=200), nullable=True),
    sa.Column('kingdom', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_table('plant_photo_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['plant_photos.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_photo_ids_id'), 'plant_photo_ids', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_photo_ids_id'), table_name='plant_photo_ids')
    op.drop_table('plant_photo_ids')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_plant_photos_id'), table_name='plant_photos')
    op.drop_table('plant_photos')
    op.drop_index(op.f('ix_leafs_id'), table_name='leafs')
    op.drop_table('leafs')
    # ### end Alembic commands ###
