"""update_leaf

Revision ID: d5b113ed12fa
Revises: f78978eac850
Create Date: 2025-04-29 18:59:30.572706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b113ed12fa'
down_revision: Union[str, None] = 'f78978eac850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leafs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leafs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leafs', type_='foreignkey')
    op.drop_column('leafs', 'user_id')
    # ### end Alembic commands ###
