"""create_leaf

Revision ID: f78978eac850
Revises: 7e646007cf96
Create Date: 2025-04-29 18:55:46.154536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78978eac850'
down_revision: Union[str, None] = '7e646007cf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leafs', sa.Column('diseases', sa.Text(), nullable=True))
    op.add_column('leafs', sa.Column('treatment', sa.Text(), nullable=True))
    op.add_column('leafs', sa.Column('prevention', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leafs', 'prevention')
    op.drop_column('leafs', 'treatment')
    op.drop_column('leafs', 'diseases')
    # ### end Alembic commands ###
